show_scatter   = yes
show_line      = yes
show_histogram = yes
show_heatmap   = yes
show_tile      = yes
show_highlight = yes
use_rules      = yes

<<include colors_fonts_patterns.conf>>
<<include ideogram.conf>>
<<include ticks.conf>>
<<include etc/housekeeping.conf>>

<image>
<<include etc/image.conf>>
</image>

karyotype = data/1.karyotype

chromosomes_units   = 2000000
chromosomes_reverse = a1,a2,a3,a4,a5,a6,a7
chromosomes_order   = b1,b2,b3,b4,b5,b6,b7,a7,a6,a5,a4,a3,a2,a1

############################################################
# Links
############################################################

<links>

z         = 0
radius    = 0.49r
thickness = 1p

<link>

z         = 60
color     = grey
thickness = 1p
file      = data/8.cross.link

<rules>

<rule>
condition = var(chr1) eq "a1"
color = 215,99,100
</rule>

<rule>
condition = var(chr1) eq "a2"
color = 255,140,0
</rule>

<rule>
condition = var(chr1) eq "a3"
color = 241,215,126
</rule>

<rule>
condition = var(chr1) eq "a4"
color = 177,206,70
</rule>

<rule>
condition = var(chr1) eq "a5"
color = 0,206,209
</rule>

<rule>
condition = var(chr1) eq "a6"
color = 95,151,210
</rule>

<rule>
condition = var(chr1) eq "a7"
color = 147,148,231
</rule>

</rules>

</link>

<link>

z         = 40
color     = grey
thickness = 1p
file      = data/8.link

<rules>

<rule>
condition = var(chr1) eq "a1"
color = 215,99,100
</rule>

<rule>
condition = var(chr1) eq "a2"
color = 255,140,0
</rule>

<rule>
condition = var(chr1) eq "a3"
color = 241,215,126
</rule>

<rule>
condition = var(chr1) eq "a4"
color = 177,206,70
</rule>

<rule>
condition = var(chr1) eq "a5"
color = 0,206,209
</rule>

<rule>
condition = var(chr1) eq "a6"
color = 95,151,210
</rule>

<rule>
condition = var(chr1) eq "a7"
color = 147,148,231
</rule>

</rules>

</link>

</links>

############################################################
# Tracks
############################################################

<plots>

<plot>

type        = line
color       = 218,165,0
thickness   = 1p
file        = data/3.GC_content

r0          = 0.50r
r1          = 0.50r+100p

orientation = out

min         = 0.35
max         = 0.55

max_gap     = 1u

<backgrounds>
<background>
color = 245,245,245
</background>
</backgrounds>

</plot>

<plot>

type        = histogram
file        = data/4.Genedensity

color       = 95,151,210
fill_color  = 95,151,210
thickness   = 2p

r0          = 0.50r+120p
r1          = 0.50r+220p

orientation = out

min         = 0
max         = 75

<backgrounds>
<background>
color = 245,245,245
</background>
</backgrounds>

</plot>

<plot>

type    = heatmap
file    = data/5.Copia.density

color   = greens-9-seq

r1      = 0.50r+240p
r0      = 0.50r+340p

min     = 0
max     = 100

</plot>

<plot>

type    = heatmap
file    = data/6.Gypsy.density

color   = greens-9-seq

r1      = 0.50r+360p
r0      = 0.50r+460p

</plot>

<plot>

type    = heatmap
file    = data/7.DNATE.density

color   = greens-9-seq

r1      = 0.50r+480p
r0      = 0.50r+580p

</plot>

</plots>
